---
version: '2'
services:
  db:
    image: postgres:latest
    container_name: postgres-instance
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5434:5432

  adminer:
    image: adminer
    container_name: adminer-instance
    restart: always
    ports:
      - 8080:8080